#!/usr/bin/env python3
"""
COTW End-to-End Game Progression Test (Gold Safety Net + Quest Items Economy)
DeviceID: test050726

Economy strategy:
  1. Start with putGold (100k) — GOLD SAFETY NET, untouched unless items exhausted
  2. Primary economy: quest rewards → collectQ → use items → speedUpItems
  3. speedUpItems BEFORE speedUpGold (last resort)
  4. TRACK at which Townhall level gold was first used
  5. Spawn monsters & resources near user, attack/gather

Data tracked:
  - TH level where gold first used (gold_first_th_level)
  - Item usage count vs item obtain count
  - Gold used total
  - Per-phase timing

Proxy: localhost:9000/api/ → COTW server
"""
import urllib.request
import json
import time
import sys
import os
import datetime

BASE = "http://localhost:9000/api"
DEVICE_ID = "test050726"
ID_USER = None
USER_COORDS = [695, 649]

# ── Gold Safety Net Tracking ──────────────────────────────────────────
GOLD_SAFETY_NET = 100000         # gold from putGold, untouched unless needed
GOLD_USED = 0                    # total gold spent via speedUpGold
GOLD_FIRST_TH_LEVEL = None       # TH level when gold was first used
ITEMS_USED_COUNT = 0             # items consumed via speedUpItems
ITEMS_OBTAINED_COUNT = 0         # items seen in quest rewards

# ── Timing database ───────────────────────────────────────────────────
TIMINGS = []  # list of dicts: phase, action, endpoint, http, elapsed_ms, result

def record_timing(phase, action, endpoint, http_code, elapsed_ms, result):
    TIMINGS.append({
        "phase": phase,
        "action": action,
        "endpoint": endpoint[:80],
        "http": http_code,
        "elapsed_ms": elapsed_ms,
        "result": str(result)[:20]
    })

def generate_timing_report():
    """Write e2e_timing_report.md from TIMINGS with gold safety net data."""
    if not TIMINGS:
        return
    report_path = os.path.join(os.path.dirname(__file__), "e2e_timing_report.md")
    total_ms = sum(t["elapsed_ms"] for t in TIMINGS)
    total_calls = len(TIMINGS)

    lines = []
    lines.append("# E2E Timing Report — Gold Safety Net + Quest Items Economy\n")
    lines.append(f"**Date**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    lines.append(f"**Total calls**: {total_calls}  \n")
    lines.append(f"**Total time**: {total_ms}ms ({total_ms/1000:.1f}s)  \n")
    lines.append(f"**Average**: {total_ms/total_calls:.0f}ms/call  \n")
    lines.append("")
    lines.append("## Gold Safety Net Tracking\n")
    lines.append(f"| Metric | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Gold safety net (putGold) | {GOLD_SAFETY_NET:,} |")
    lines.append(f"| Gold actually spent | {GOLD_USED:,} |")
    lines.append(f"| Gold first used at TH level | {GOLD_FIRST_TH_LEVEL or 'Never used'} |")
    lines.append(f"| Items obtained from quests | {ITEMS_OBTAINED_COUNT:,} |")
    lines.append(f"| Items consumed (speedUpItems) | {ITEMS_USED_COUNT:,} |")
    lines.append(f"| Items net | {ITEMS_OBTAINED_COUNT - ITEMS_USED_COUNT:,} |")
    lines.append("")

    # Slowest calls summary
    sorted_timings = sorted(TIMINGS, key=lambda t: t["elapsed_ms"], reverse=True)
    lines.append("## Slowest Calls (Top 10)\n")
    lines.append("| # | Phase | Endpoint | ms |")
    lines.append("|---|---|---|---|")
    for i, t in enumerate(sorted_timings[:10]):
        lines.append(f"| {i+1} | {t['phase']} | {t['endpoint']} | {t['elapsed_ms']} |")
    lines.append("")

    # Summary by phase
    lines.append("## Summary by Phase\n")
    phases = {}
    for t in TIMINGS:
        p = t["phase"]
        if p not in phases:
            phases[p] = {"calls": 0, "total_ms": 0}
        phases[p]["calls"] += 1
        phases[p]["total_ms"] += t["elapsed_ms"]
    lines.append("| Phase | Calls | Total ms | Avg ms |")
    lines.append("|---|---|---|---|")
    for p, d in phases.items():
        lines.append(f"| {p} | {d['calls']} | {d['total_ms']} | {d['total_ms']//d['calls']} |")
    lines.append("")

    # Full per-call table
    lines.append("## Per-Call Timing\n")
    lines.append("| # | Phase | Action | Endpoint | HTTP | ms | Result |")
    lines.append("|---|---|---|---|---|---|---|")
    for i, t in enumerate(TIMINGS):
        lines.append(f"| {i+1} | {t['phase']} | {t['action']} | {t['endpoint']} | {t['http']} | {t['elapsed_ms']} | {t['result']} |")
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated by E2E test on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_")

    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"\n  📊 Reporte guardado: {report_path}\n")


# ── Helpers ──────────────────────────────────────────────────────────

def api(endpoint, silent=False, phase="", action=""):
    """Call COTW API. Returns parsed JSON dict or None on network error."""
    global ID_USER, USER_COORDS
    url = f"{BASE}/{endpoint}"
    if "deviceId=" not in url:
        sep = "&" if "?" in url else "?"
        url += f"{sep}deviceId={DEVICE_ID}"
    if ID_USER and "idUser=" not in url:
        url += f"&idUser={ID_USER}"

    for attempt in range(2):
        try:
            start = time.time()
            with urllib.request.urlopen(url, timeout=60) as resp:
                data = json.loads(resp.read().decode())
            elapsed = int((time.time() - start) * 1000)
            http_code = resp.status
        except Exception as e:
            if not silent:
                print(f"  🌐 NETWORK ERROR (attempt {attempt+1}): {e}")
            time.sleep(1)
            continue

        result = data.get("result")
        record_timing(phase, action, endpoint, http_code, elapsed, result)

        if result == -1:
            msg = (data.get("Message") or data.get("message") or "Unknown error")[:300]
            print(f"  ❌ result=-1: {msg}")
        elif result == 0:
            msg = (data.get("Message") or data.get("message") or "")[:150]
            if not silent:
                print(f"  ⚠️  result=0: {msg}")
        elif not silent:
            size = len(json.dumps(data, default=str))
            print(f"  ✅ HTTP 200 | result={result} | {elapsed}ms | {size}B")

        # Auto-extract ID_USER from User._id
        u = data.get("User")
        if u and u.get("_id"):
            uid = u["_id"]
            ID_USER = uid.get("$oid", uid) if isinstance(uid, dict) else uid

        # Auto-extract coordinates
        p = data.get("User", {}).get("Player", {})
        coords = p.get("Coordinates")
        if coords:
            USER_COORDS = coords

        return data

    return None


def node_of(data, id_building):
    if not data:
        return None
    for b in (data.get("User", {}) or {}).get("Buildings", []):
        if b.get("idBuilding") == id_building:
            return b.get("Node")
    return None


def level_of(data, id_building):
    if not data:
        return 0
    for b in (data.get("User", {}) or {}).get("Buildings", []):
        if b.get("idBuilding") == id_building:
            return b.get("Level", 0)
    return 0


def has_building(data, id_building):
    if not data:
        return False
    return any(
        b.get("idBuilding") == id_building
        for b in (data.get("User", {}) or {}).get("Buildings", [])
    )


def collect_all(data, phase=""):
    """Attempt to collect from all existing building nodes."""
    if not data:
        return
    blds = (data.get("User", {}) or {}).get("Buildings", [])
    for b in blds:
        node = b.get("Node")
        if node:
            r = api(f"BUILDINGS?action=collect&Node={node}", silent=True, phase=phase, action="collect")
            if r and r.get("result") == 1:
                resources = r.get("Resources", {})
                gold = resources.get("Gold", {}) if isinstance(resources, dict) else {}
                gold_qty = gold.get("Quantity", "?")
                print(f"    Recolectado Node={node} | gold={gold_qty}")


def get_resources(data):
    """Return dict of current resource quantities."""
    u = data.get("User", {}) if data else {}
    return {
        "Gold": (u.get("Gold", {}) or {}).get("Quantity", 0) or 0,
        "Food": (u.get("Food", {}) or {}).get("Quantity", 0) or 0,
        "Wood": (u.get("Wood", {}) or {}).get("Quantity", 0) or 0,
        "Stone": (u.get("Stone", {}) or {}).get("Quantity", 0) or 0,
        "Ore": (u.get("Ore", {}) or {}).get("Quantity", 0) or 0,
    }


def get_items(data):
    """Return list of items from User.Items."""
    u = data.get("User", {}) if data else {}
    return u.get("Items", []) or []


def count_items(data):
    """Count total item quantity in inventory."""
    items = get_items(data)
    total = 0
    for item in items:
        total += item.get("Quantity", 1) or 1
    return total


def check_quests(phase=""):
    """Check quests and collect any completed rewards. Returns data if collected."""
    global ITEMS_OBTAINED_COUNT
    r = api("QUEST?action=rewards&idQuest=0", silent=True, phase=phase, action="quest_rewards")
    if r and r.get("result") == 1:
        quests = r.get("Quests", []) or []
        completed = [q for q in quests if q.get("Completed")]
        if completed:
            print(f"    🎯 Misiones completadas: {len(completed)}")
            for q in completed:
                qid = q.get("idQuest", q.get("_id", "?"))
                cr = api(f"QUEST?action=collectQ&idQuest={qid}", silent=True, phase=phase, action=f"collectQ_{qid}")
                if cr and cr.get("result") == 1:
                    items = cr.get("User", {}).get("Items", []) or []
                    if items:
                        item_qty = sum(i.get("Quantity", 1) or 1 for i in items)
                        ITEMS_OBTAINED_COUNT += item_qty
                        print(f"      Cobrada misión {qid}: {item_qty} items (total: {ITEMS_OBTAINED_COUNT})")
                    else:
                        print(f"      Cobrada misión {qid}")
            return True
        else:
            print(f"    🎯 Sin misiones completadas (de {len(quests)} pendientes)")
            return True  # quest system works, just nothing to collect
    return False


def check_daily_quests(phase=""):
    """Check and collect daily quests."""
    global ITEMS_OBTAINED_COUNT
    r = api("QUEST?action=rewardsD&idQuest=0", silent=True, phase=phase, action="quest_rewardsD")
    if r and r.get("result") == 1:
        dq = r.get("DailyQuests", []) or []
        completed = [q for q in dq if q.get("Completed")]
        if completed:
            print(f"    📅 Diarias completadas: {len(completed)}")
            cr = api("QUEST?action=collectD", silent=True, phase=phase, action="collectD")
            if cr and cr.get("result") == 1:
                items = cr.get("User", {}).get("Items", []) or []
                if items:
                    item_qty = sum(i.get("Quantity", 1) or 1 for i in items)
                    ITEMS_OBTAINED_COUNT += item_qty
                    print(f"      📅 Diarias cobradas: {item_qty} items (total: {ITEMS_OBTAINED_COUNT})")
                else:
                    print(f"      📅 Diarias cobradas")
                return True
    return False


def collect_daily_reward(phase=""):
    """Collect daily reward."""
    r = api("USER?action=dailyReward", silent=True, phase=phase, action="dailyReward")
    if r and r.get("result") == 1:
        print(f"    🎁 Recompensa diaria cobrada")
        return True
    return False


def open_resource_chests(phase=""):
    """Try to open each resource chest item."""
    global ITEMS_OBTAINED_COUNT
    data = api("USER?action=loginJustUser", silent=True, phase=phase, action="login_items_check")
    if not data:
        return
    items = get_items(data)
    chests = [i for i in items if i.get("Type", "").lower() in ("chest", "chests")]
    if not chests:
        return
    print(f"    🎁 Abriendo {len(chests)} cofres...")
    for chest in chests:
        r = api(f"ITEMS?action=materialChest&idItem={chest['idItem']}&Quantity={chest.get('Quantity',1)}",
                silent=True, phase=phase, action="open_chest")
        if r and r.get("result") == 1:
            print(f"      Cofre #{chest['idItem']} abierto")


def count_speedup_items(data):
    """Count speedup items in inventory."""
    items = get_items(data)
    total = 0
    for item in items:
        if "speed" in item.get("Type", "").lower() or item.get("Type", "").lower() in ("speedup", "speed"):
            total += item.get("Quantity", 1) or 1
    return total


# ── GOLD SAFETY NET: try speedUpItems first, speedUpGold as last resort ────

def try_complete_construct(cid, label="", phase="", current_th_level=None):
    """
    Try to complete construct using:
      1. speedUpGold (gold safety net - PRIMARY — bootstrap quest economy)
      2. speedUpItems (quest items - SECONDARY)
    
    Returns True if construct seems done.
    Tracks gold/items usage and TH level of first gold use.
    """
    global GOLD_USED, ITEMS_USED_COUNT, GOLD_FIRST_TH_LEVEL
    
    if not cid:
        return False
    time.sleep(1)
    r = api(f"CONSTRUCT?action=remainingTime&idConstruct={cid}", silent=True, phase=phase, action=f"remainingTime_{label}")
    if r and r.get("result") == 1:
        remaining = r.get("RemainingTime", 999)
        status = r.get("Status", r.get("status", ""))
        print(f"    {label}: remainingTime={remaining}s status={status}")
        if isinstance(remaining, (int, float)):
            if remaining <= 1:
                return True
            
            # ── STEP 1: speedUpGold FIRST (bootstrap quest economy) ──
            print(f"    {label}: speedUpGold...")
            speed_r = api(f"CONSTRUCT?action=speedUpGold&idConstruct={cid}", silent=True, phase=phase, action=f"speedUpGold_{label}")
            if speed_r and speed_r.get("result") == 1:
                cost_obj = speed_r.get("Cost", {}) or speed_r.get("cost", {})
                cost = cost_obj.get("Gold", cost_obj.get("Quantity", 0)) if isinstance(cost_obj, dict) else 0
                if not cost:
                    cost = 100
                GOLD_USED += cost
                if GOLD_FIRST_TH_LEVEL is None and current_th_level is not None:
                    GOLD_FIRST_TH_LEVEL = current_th_level
                    print(f"    ⚠️  ** PRIMER USO DE GOLD en TH Lvl {current_th_level} **")
                print(f"    {label}: 💰 speedUpGold OK (cost={cost}, total gold used: {GOLD_USED})")
                return True
            elif speed_r and speed_r.get("result") == -1:
                msg = speed_r.get("Message", "")[:150] if speed_r else ""
                print(f"    {label}: speedUpGold falló ({msg}), probando items...")
            
            # ── STEP 2: Try speedUpItems (quest items - SECONDARY) ──
            time_items_data = api("ITEMS?action=timeItems", silent=True, phase=phase, action="timeItems")
            if time_items_data and time_items_data.get("result") == 1:
                items_list = time_items_data.get("Items", []) or []
                if items_list:
                    for si in items_list[:5]:
                        sid = si.get("idItem", "1001")
                        sqty = min(si.get("Quantity", 1) or 1, 5)
                        sp_r = api(f"CONSTRUCT?action=speedUpItems&idConstruct={cid}&Items={sid}.{sqty}",
                                   silent=True, phase=phase, action=f"speedUpItems_{label}")
                        if sp_r and sp_r.get("result") == 1:
                            ITEMS_USED_COUNT += sqty
                            print(f"    {label}: ⏱️ speedUpItems OK (Item #{sid} x{sqty}) [items used total: {ITEMS_USED_COUNT}]")
                            return True
                        elif sp_r and sp_r.get("result") == -1:
                            msg = sp_r.get("Message", "")
                            if "RESOURCES" in msg.upper() or "ITEM" in msg.upper():
                                continue
                            break
            
            # ── STEP 3: Last resort — use items from inventory directly
            # ... (existing fallback stays unchanged)
                print(f"    {label}: speedUpGold → {msg if msg else 'failed'}")
                
                # Try waiting and retrying
                print(f"    {label}: Esperando 3s y reintentando...")
                time.sleep(3)
                r2 = api(f"CONSTRUCT?action=remainingTime&idConstruct={cid}", silent=True, phase=phase, action=f"remainingTime2_{label}")
                if r2 and r2.get("result") == 1:
                    rem2 = r2.get("RemainingTime", 999)
                    print(f"    {label}: retry remainingTime={rem2}s")
                    if rem2 <= 1 or rem2 < remaining:
                        return rem2 <= 1
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:200]
        if "not" in msg.lower() or "exist" in msg.lower() or "invalid" in msg.lower():
            print(f"    {label}: constructo ya completado ({msg[:80]})")
            return True
        print(f"    {label}: remainingTime error: {msg}")
    return False


def refresh(phase=""):
    """Re-login and return data."""
    data = api("USER?action=loginJustUser", silent=True, phase=phase, action="refresh")
    return data


def section(n, title):
    print(f"\n{'=' * 60}")
    print(f"  PHASE {n}: {title}")
    print(f"{'=' * 60}")


# ── Quest Economy Helper ─────────────────────────────────────────────

def process_quests_and_items(phase_prefix, sub_label="", force_items=False):
    """After an action, check quests, use items, open chests, collect daily."""
    # 1. Check and collect quests
    check_quests(phase=phase_prefix)
    # 2. Check daily quests
    check_daily_quests(phase=phase_prefix)
    # 3. Try daily reward
    collect_daily_reward(phase=phase_prefix)
    # 4. Open resource chests
    open_resource_chests(phase=phase_prefix)
    # 5. Use resource items if needed
    use_resource_items(phase=phase_prefix, force=force_items)


def use_resource_items(phase="", force=False):
    """Use resource items from inventory if resources are low."""
    global ITEMS_USED_COUNT
    data = api("USER?action=loginJustUser", silent=True, phase=phase, action="login_resource_check")
    if not data:
        return 0
    res = get_resources(data)
    items = get_items(data)

    # Find resource items (non-speedup, non-chest)
    res_items = [i for i in items if i.get("Type", "").lower() == "resources" or i.get("Type", "").lower() == "resource"]

    used = 0
    for item in res_items:
        qty = item.get("Quantity", 0) or 0
        if qty > 0:
            # Check if gold is low (primary resource we care about)
            if res.get("Gold", 0) < 50000 or force:
                use_qty = min(qty, 5)
                r = api(f"ITEMS?action=use&idItem={item['idItem']}&Quantity={use_qty}",
                        silent=True, phase=phase, action="use_item")
                if r and r.get("result") == 1:
                    print(f"      📦 Item #{item['idItem']} usado x{use_qty}")
                    used += use_qty
                    ITEMS_USED_COUNT += use_qty
                    # Re-check resources
                    res = get_resources(r)
                    if res.get("Gold", 0) >= 100000:
                        break

    return used


def get_th_level(data):
    """Get current Townhall level."""
    return level_of(data, 1001)


# ── Main test flow ───────────────────────────────────────────────────

section(1, "Crear usuario + setup + gold safety net")
print("  ⚠️  Gold safety net: 100k gold disponible, NO usar a menos que items fallen")

data = api("USER?action=reset", phase="1-Reset", action="reset")
if data is None:
    print("FATAL: No se pudo conectar al servidor (reset)")
    sys.exit(1)
if data.get("result") == 1:
    u = data.get("User", {})
    uid = u.get("_id", {})
    ID_USER = uid.get("$oid", uid) if isinstance(uid, dict) else uid
    print(f"  Usuario creado: {ID_USER}")
else:
    msg = data.get("Message", "")[:200]
    print(f"  reset result={data.get('result')}: {msg}")

data = refresh(phase="1-Login")
if data is None or data.get("result") != 1:
    print("FATAL: No se pudo hacer login")
    sys.exit(1)

user = data.get("User", {})
player = user.get("Player", {})
coords = player.get("Coordinates", "?")
print(f"  Username: {player.get('UserName', '?')}")
print(f"  Coordenadas: {coords}")
blds = user.get("Buildings", [])
print(f"  Buildings: {len(blds)}")
for b in blds:
    print(f"    - idBuilding={b.get('idBuilding')} Lvl={b.get('Level')} Node={b.get('Node')}")

th_node = node_of(data, 1001)
th_lvl = level_of(data, 1001)
print(f"  Townhall Node={th_node} Lvl={th_lvl}")

# Collect initial rewards
collect_daily_reward(phase="1-Init")
process_quests_and_items("1-Init")

# ── Setup gold safety net (putGold — 100k, untouched unless needed) ──
print("\n  💰 Setup: putGold 100k (safety net — untouched unless items exhausted)")
r = api("DEMO?action=putGold&deviceId=test050726", silent=True, phase="1-Gold", action="putGold")
if r and r.get("result") == 1:
    user_data = r.get("User", {})
    gold_qty = (user_data.get("Gold", {}) or {}).get("Quantity", 0)
    print(f"    Gold safety net: {gold_qty:,} disponible")

# ─────────────────────────────────────────────────────────────────────
section(2, "Construir infraestructura (quest items economy)")

# Collect initial resources
collect_all(data, phase="2-Collect")

# Build needed infrastructure
build_plan = [
    (1002, 1, 2, "Wall"),
    (2002, 4, 14, "Academy"),
    (2003, 5, 15, "Hospital"),
    (2007, 6, 16, "Forge"),
    (2006, 9, 19, "Embassy"),
    (2008, 7, 17, "Pit"),
    (2009, 18, 20, "Wishing Well"),
]

data = refresh(phase="2-Refresh")
existing_ids = set()
if data:
    existing_ids = {b.get("idBuilding") for b in (data.get("User", {}) or {}).get("Buildings", [])}
print(f"  Ya existen: {sorted(existing_ids)}")

for bid, node1, node2, name in build_plan:
    if bid in existing_ids:
        print(f"  {name} (id={bid}) ya existe")
        continue

    for node_attempt in [node1, node2]:
        print(f"\n  Construyendo {name} (id={bid}) node={node_attempt}...")
        r = api(f"BUILDINGS?action=construct&idBuilding={bid}&Node={node_attempt}",
                silent=True, phase="2-Build", action=f"construct_{name}")
        if r is None:
            continue
        if r.get("result") == 1:
            cid = r.get("idConstruct")
            print(f"    ✅ Construct iniciado: {cid}")
            if cid:
                try_complete_construct(cid, name, phase="2-Build", current_th_level=th_lvl)
                # QUEST ECONOMY: collect rewards after building
                process_quests_and_items("2-Build", name)
            break
        elif r.get("result") == -1:
            msg = r.get("Message", "")[:200]
            if "Busy" in msg:
                print(f"    Node busy, probando otro...")
                continue
            print(f"    No se pudo: {msg}")
            break

# Collect again after any completes
time.sleep(1)
data = refresh(phase="2-Refresh2")
collect_all(data, phase="2-Collect2")
process_quests_and_items("2-PostBuild")

# ─────────────────────────────────────────────────────────────────────
section(3, "Mejorar Townhall (quest items economy — track gold first use)")

data = refresh(phase="3-Refresh")
th_node = node_of(data, 1001)
th_lvl = level_of(data, 1001)
print(f"  Townhall Node={th_node} Lvl={th_lvl}")

if th_node:
    for i in range(5):  # Try 5 levels with quest rewards
        th_lvl = get_th_level(data)
        print(f"\n  ═══ Townhall Level Up #{i+1} (current Lvl={th_lvl}) ═══")
        
        # Collect quests/items first to ensure resources
        process_quests_and_items("3-TH", f"pre_level_{i+1}")

        r = api(f"BUILDINGS?action=levelUpB&Node={th_node}",
                silent=True, phase="3-Townhall", action=f"levelUp_{i+1}")
        if r and r.get("result") == 1:
            cid = r.get("idConstruct")
            if cid:
                print(f"  ✅ Townhall mejorado (intento {i+1}) construct={cid}")
                try_complete_construct(cid, f"TH Lvl {i+1}", phase="3-Townhall", current_th_level=th_lvl)
                # QUEST ECONOMY: collect rewards after upgrade
                process_quests_and_items("3-TH", f"post_level_{i+1}")
                data = refresh(phase="3-Refresh")
                new_th_lvl = get_th_level(data)
                print(f"  Townhall ahora Lvl={new_th_lvl} (antes Lvl={th_lvl})")
                th_lvl = new_th_lvl
        else:
            msg = r.get("Message", "")[:200] if r else "no response"
            print(f"  No se pudo mejorar más: {msg}")
            if "RESOURCES" in msg:
                print(f"  Sin recursos — usando items de misiones...")
                use_resource_items(phase="3-TH", force=True)
                continue  # retry
            break
        time.sleep(0.5)
else:
    print("  ERROR: No se encontró Townhall en buildings")

process_quests_and_items("3-PostTH", force_items=True)
th_lvl = get_th_level(data) if data else th_lvl
print(f"\n  📊 TH after upgrades: Lvl {th_lvl}")

# ─────────────────────────────────────────────────────────────────────
section(4, "Spawn monsters & resources + attack/gather")

cx, cy = USER_COORDS
print(f"  Usuario en [{cx}, {cy}]")

# Spawn monsters near user
print(f"\n  👹 Spawning monsters near [{cx}, {cy}]...")
r = api("DEMO?action=spawnMonsters&deviceId=test050726", silent=True, phase="4-Monsters", action="spawnMonsters")
if r and r.get("result") == 1:
    count = r.get("monstersSpawned", 0)
    print(f"    ✅ {count} monsters spawned at [{r.get('baseX')}, {r.get('baseY')}]")

# Spawn resources near user
print(f"\n  🌿 Spawning resources near [{cx}, {cy}]...")
r = api("DEMO?action=spawnResources&deviceId=test050726", silent=True, phase="4-Resources", action="spawnResources")
if r and r.get("result") == 1:
    print(f"    ✅ {r.get('resourcesSpawned')} resource nodes spawned at [{r.get('baseX')}, {r.get('baseY')}]")

# Scout nearby to find spawned entities
print(f"\n  🔍 Scouting nearby tiles...")
for sx, sy in [(cx-2, cy-2), (cx+2, cy+2), (cx, cy+4), (cx+4, cy), (cx-3, cy+1)]:
    sx = max(1, sx)
    sy = max(1, sy)
    r = api(f"WORLDMAP?action=scout&x={sx}&y={sy}", silent=True, phase="4-Map", action="scout")
    if r and r.get("result") == 1:
        print(f"    Scout ({sx},{sy}) → OK")
        map_data = r.get("Map", [])
        if map_data:
            for item in map_data[:5]:
                item_type = item.get("Type", "?")
                item_name = item.get("Name", "?")
                item_lvl = item.get("Level", "?")
                print(f"      Tile: {item_type} / {item_name} Lvl={item_lvl}")
        break
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:100]
        if "haste" in msg.lower():
            break

# Attack monsters near user
print(f"\n  ⚔️ Attacking monsters near user...")
for mx_off, my_off in [(1, 1), (2, 2), (-1, 1), (3, 0), (0, 3)]:
    mx = max(1, cx + mx_off)
    my = max(1, cy + my_off)
    r = api(f"WORLDMAP?action=monster&x={mx}&y={my}&Troops=Infantry.1.1",
            silent=True, phase="4-Attack", action=f"monster_{mx}_{my}")
    if r and r.get("result") == 1:
        print(f"    ✅ Monster ({mx},{my}) attacked successfully!")
        process_quests_and_items("4-Attack", f"monster_{mx}_{my}")
        break
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:150]
        if "Monster" in msg and ("not" in msg.lower() or "exist" in msg.lower()):
            continue
        elif "Troops" in msg:
            print(f"    ⚠️  Monster ({mx},{my}): need troops - {msg}")
            break
        print(f"    Monster ({mx},{my}): {msg}")

# Gather resources near user
print(f"\n  🌾 Gathering resources near user...")
for gx_off, gy_off in [(-1, 2), (2, -1), (4, 1), (1, 4), (-2, 3)]:
    gx = max(1, cx + gx_off)
    gy = max(1, cy + gy_off)
    r = api(f"WORLDMAP?action=gather&x={gx}&y={gy}&Troops=Infantry.1.1",
            silent=True, phase="4-Gather", action=f"gather_{gx}_{gy}")
    if r and r.get("result") == 1:
        march = r.get("March", r.get("march", {}))
        mid = march.get("_id", {}) or march.get("_id", "")
        if isinstance(mid, dict):
            mid = mid.get("$oid", "")
        print(f"    ✅ Gather ({gx},{gy}) march={mid}")
        if mid:
            api(f"WORLDMAP?action=syncMarch&idMarch={mid}", silent=True, phase="4-Gather", action="syncMarch")
            api(f"WORLDMAP?action=goHome&idMarch={mid}", silent=True, phase="4-Gather", action="goHome")
            print(f"      Marcha sincronizada y regresada")
        break
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:150]
        if "Resources" in msg and ("not" in msg.lower() or "exist" in msg.lower()):
            continue
        elif "Troops" in msg:
            print(f"    ⚠️  Gather ({gx},{gy}): need troops - {msg}")
            break
        print(f"    Gather ({gx},{gy}): {msg}")

process_quests_and_items("4-PostMap", force_items=True)

# ─────────────────────────────────────────────────────────────────────
section(5, "Entrenar tropas (quest items economy)")

data = refresh(phase="5-Refresh")
bld_list = []
if data:
    bld_list = (data.get("User", {}) or {}).get("Buildings", [])
existing_ids = {b.get("idBuilding") for b in bld_list}
print(f"  Edificios disponibles: {sorted(existing_ids)}")

# Training buildings to construct if missing
training_builds = [
    (2014, 10, "Barracks (Infantry)"),
    (2012, 12, "Archer Range"),
    (2013, 11, "Stable (Cavalry)"),
    (2015, 13, "Siege Workshop"),
]

for tbid, tnode, tname in training_builds:
    if tbid not in existing_ids:
        print(f"\n  Construyendo {tname} (id={tbid})...")
        r = api(f"BUILDINGS?action=construct&idBuilding={tbid}&Node={tnode}",
                silent=True, phase="5-TrainBuild", action=f"construct_{tname.replace(' ','')}")
        if r and r.get("result") == 1:
            cid = r.get("idConstruct")
            print(f"    ✅ Construido: {cid}")
            if cid:
                try_complete_construct(cid, tname, phase="5-TrainBuild", current_th_level=th_lvl)
                process_quests_and_items("5-TrainBuild", tname)
        elif r and r.get("result") == -1:
            msg = r.get("Message", "")[:200]
            print(f"    No construido: {msg}")

# Use items before training
process_quests_and_items("5-PreTrain", force_items=True)

# Now train troops (use quest-reward items for resources)
train_plan = [
    (2014, "Infantry", 1, 5),
    (2012, "Archer", 1, 3),
    (2013, "Cavalry", 1, 2),
    (2015, "Siege", 1, 1),
]

for tbl_id, ttype, lvl, qty in train_plan:
    print(f"\n  Entrenando {ttype} Lvl.{lvl} x{qty}...")
    r = api(f"BUILDINGS?action=train&idBuilding={tbl_id}&Level={lvl}&Quantity={qty}",
            silent=True, phase="5-Train", action=f"train_{ttype}")
    if r and r.get("result") == 1:
        cid = r.get("idConstruct")
        if cid:
            print(f"    ✅ Entrenamiento iniciado: {cid}")
            try_complete_construct(cid, f"{ttype}", phase="5-Train", current_th_level=th_lvl)
            process_quests_and_items("5-Train", ttype)
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:200]
        print(f"    No entrenado: {msg}")
        if "RESOURCES" in msg:
            print(f"    Sin recursos — usando items...")
            use_resource_items(phase="5-Train", force=True)

process_quests_and_items("5-PostTrain", force_items=True)

# ─────────────────────────────────────────────────────────────────────
section(6, "Investigar (quest items economy)")

data = refresh(phase="6-Refresh")
print(f"  Academy exists: {has_building(data, 2002)}")

process_quests_and_items("6-PreResearch", force_items=True)

for rid in [1, 2, 3, 4, 5]:
    print(f"\n  Investigando tech id={rid}...")
    r = api(f"BUILDINGS?action=research&idResearch={rid}",
            silent=True, phase="6-Research", action=f"research_{rid}")
    if r and r.get("result") == 1:
        cid = r.get("idConstruct")
        if cid:
            print(f"    ✅ Investigación iniciada: {cid}")
            try_complete_construct(cid, f"Research {rid}", phase="6-Research", current_th_level=th_lvl)
            process_quests_and_items("6-Research", f"tech_{rid}")
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:250]
        print(f"    No investigado: {msg}")
        if "requirements" in msg.lower() or "Config" in msg or "RESOURCES" in msg:
            print(f"    (saltando más invest. — requisitos no cumplidos)")
            break

process_quests_and_items("6-PostResearch", force_items=True)

# ─────────────────────────────────────────────────────────────────────
section(7, "Héroe (quest items economy)")

process_quests_and_items("7-PreHero", force_items=True)

# Status
r = api("HERO?action=status", phase="7-Hero", action="status")
if r and r.get("result") == 1:
    u = r.get("User", {}) or {}
    hero = u.get("Hero", {}) or {}
    hid = hero.get("idHero", hero.get("_id", "?"))
    hlvl = hero.get("Level", "?")
    hexp = hero.get("Exp", hero.get("Experience", "?"))
    print(f"  Héroe: {hid} Level={hlvl} Exp={hexp}")

    # Level up
    r2 = api("HERO?action=levelUpH", silent=True, phase="7-Hero", action="levelUpH")
    if r2 and r2.get("result") == 1:
        print(f"  ✅ Hero levelUpH OK")
        process_quests_and_items("7-Hero", "levelUpH")
    elif r2 and r2.get("result") == -1:
        msg = r2.get("Message", "")[:200]
        print(f"  levelUpH: {msg}")

    # Activate skill
    r3 = api("HERO?action=activateSkill", silent=True, phase="7-Hero", action="activateSkill")
    if r3 and r3.get("result") == 1:
        print(f"  ✅ activateSkill OK")
    elif r3 and r3.get("result") == -1:
        msg = r3.get("Message", "")[:200]
        print(f"  activateSkill: {msg}")
else:
    msg = r.get("Message", "")[:200] if r else "no response"
    print(f"  Hero status: {msg}")

# Prison feed
r = api("HERO?action=prisonFeed", silent=True, phase="7-Hero", action="prisonFeed")
if r and r.get("result") == 1:
    print(f"  ✅ prisonFeed OK")
elif r and r.get("result") == -1:
    print(f"  prisonFeed: {r.get('Message','?')[:150]}")

# Pit feed
r = api("HERO?action=pitFeed", silent=True, phase="7-Hero", action="pitFeed")
if r and r.get("result") == 1:
    print(f"  ✅ pitFeed OK")
elif r and r.get("result") == -1:
    print(f"  pitFeed: {r.get('Message','?')[:150]}")

process_quests_and_items("7-PostHero", force_items=True)

# ─────────────────────────────────────────────────────────────────────
section(8, "Mapa mundial + more quests")

# Use coordinates relative to user's position
cx, cy = USER_COORDS
print(f"  Usuario en [{cx}, {cy}]")

# GetQuadrant around user
qx = max(100, cx - 20)
qy = max(100, cy - 20)
print(f"  Query Quadrant ({qx},{qy})...")
r = api(f"WORLDMAP?action=getQuadrant&idKingdom=1&x={qx}&y={qy}",
        silent=False, phase="8-Map", action="getQuadrant")
if r and r.get("result") == 1:
    marches = r.get("Marches", [])
    print(f"  Quadrant: {len(marches)} marchas visibles")
elif r and r.get("result") == -1:
    print(f"  Quadrant: {r.get('Message','?')[:200]}")

# Scout near user
scout_coords = [
    (cx + 10, cy + 10),
    (cx + 20, cy + 20),
    (max(1, cx - 5), max(1, cy - 5)),
]
for sx, sy in scout_coords:
    r = api(f"WORLDMAP?action=scout&x={sx}&y={sy}", silent=True, phase="8-Map", action="scout")
    if r and r.get("result") == 1:
        print(f"  ✅ Scout ({sx},{sy}) OK")
        break
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:150]
        print(f"  Scout ({sx},{sy}): {msg}")

# Gather near user
gather_coords = [
    (cx + 5, cy + 5),
    (cx + 15, cy + 15),
    (max(1, cx - 10), max(1, cy - 10)),
]
for gx, gy in gather_coords:
    r = api(f"WORLDMAP?action=gather&x={gx}&y={gy}&Troops=Infantry.1.1",
            silent=True, phase="8-Map", action="gather")
    if r and r.get("result") == 1:
        march = r.get("March", r.get("march", {}))
        mid = march.get("_id", {}) or march.get("_id", "")
        if isinstance(mid, dict):
            mid = mid.get("$oid", "")
        print(f"  ✅ Gather ({gx},{gy}) march={mid}")
        if mid:
            api(f"WORLDMAP?action=syncMarch&idMarch={mid}", silent=True, phase="8-Map", action="syncMarch")
            api(f"WORLDMAP?action=goHome&idMarch={mid}", silent=True, phase="8-Map", action="goHome")
            print(f"    Marcha sincronizada y regresada")
        break
    elif r and r.get("result") == -1:
        msg = r.get("Message", "")[:150]
        print(f"  Gather ({gx},{gy}): {msg}")
        if "Troops" in msg or "RESOURCES" in msg:
            print(f"    (sin tropas disponibles para gather)")
            break

process_quests_and_items("8-PostMap", force_items=True)

# ─────────────────────────────────────────────────────────────────────
section(9, "More quest loops — complete as many as possible")

print(f"  Trying additional quest cycles...")
for q_cycle in range(3):
    print(f"\n  Quest cycle #{q_cycle+1}")
    process_quests_and_items("9-QuestLoop", f"cycle_{q_cycle+1}", force_items=True)
    
    # Check for any remaining quest chest
    r = api("DEMO?action=chestQuests&deviceId=test050726", silent=True, phase="9-QuestLoop", action="chestQuests")
    if r and r.get("result") == 1:
        print(f"    Quest chest reset → collecting...")
        process_quests_and_items("9-QuestLoop", f"post_chest_{q_cycle+1}", force_items=True)
    
    time.sleep(0.5)

# ─────────────────────────────────────────────────────────────────────
section(10, "Estado final")

print("  Refresh final...")
data = refresh(phase="10-Final")

if data and data.get("result") == 1:
    user = data.get("User", {})
    player = user.get("Player", {})
    buildings = user.get("Buildings", [])
    troops_container = user.get("Troops", {})
    hero = user.get("Hero", {})
    items = user.get("Items", [])

    th_final = get_th_level(data)
    print(f"\n  ┌── INFORME FINAL ──────────────────────")
    print(f"  │ Username:  {player.get('UserName', '?')}")
    print(f"  │ ID:        {ID_USER}")
    print(f"  │ Coords:    {player.get('Coordinates', '?')}")
    print(f"  │ Edificios: {len(buildings)} construidos")
    print(f"  │ Townhall:  Lvl {th_final}")
    hid = hero.get("idHero", hero.get("_id", hero.get("Name", "?")))
    print(f"  │ Héroe:     {hid} Level={hero.get('Level', '?')}")
    print(f"  │ Items:     {len(items)} en inventario")
    print(f"  │")
    print(f"  ├── GOLD SAFETY NET ────────────────────")
    print(f"  │   Safety net inicial: {GOLD_SAFETY_NET:,}")
    print(f"  │   Gold gastado:       {GOLD_USED:,}")
    print(f"  │   Gold first used:    TH Lvl {GOLD_FIRST_TH_LEVEL or 'NUNCA'}")
    print(f"  │   Items obtenidos:    {ITEMS_OBTAINED_COUNT:,}")
    print(f"  │   Items usados:       {ITEMS_USED_COUNT:,}")
    print(f"  │   Items netos:        {ITEMS_OBTAINED_COUNT - ITEMS_USED_COUNT:,}")
    print(f"  │")

    print(f"  ├── RECURSOS ───────────────────────────")
    res = get_resources(data)
    for k, v in res.items():
        print(f"  │   {k}: {v:,}")
    print(f"  │")

    print(f"  ├── EDIFICIOS ────────────────────────")
    for b in buildings:
        n = b.get("Node", "?")
        l = b.get("Level", "?")
        bid = b.get("idBuilding", "?")
        print(f"  │   Node {n:>2}: idBuilding={bid} Lvl={l}")

    print(f"  ├── TROPAS ───────────────────────────")
    troop_total = 0
    for ttype in ["Infantry", "Archer", "Cavalry", "Siege"]:
        td = troops_container.get(ttype, {})
        for tl in td.get("Troops", []):
            active = tl.get("Active", 0)
            if active > 0:
                print(f"  │   {ttype:>10} Lvl{tl.get('Level')}: {active} activas")
                troop_total += active
    if troop_total == 0:
        print(f"  │   (sin tropas)")

    print(f"  ├── ITEMS ─────────────────────────────")
    item_types = {}
    for item in items:
        t = item.get("Type", "Otros")
        if t not in item_types:
            item_types[t] = 0
        item_types[t] += item.get("Quantity", 1) or 1
    for t, q in sorted(item_types.items()):
        print(f"  │   {t}: {q} unidades")

    print(f"  │")
    print(f"  ├── TIMING ────────────────────────────")
    total_ms = sum(t["elapsed_ms"] for t in TIMINGS)
    print(f"  │   Llamadas: {len(TIMINGS)}")
    print(f"  │   Tiempo total: {total_ms}ms ({total_ms/1000:.1f}s)")
    if TIMINGS:
        avg_ms = total_ms / len(TIMINGS)
        print(f"  │   Media: {avg_ms:.0f}ms/llamada")
        sorted_t = sorted(TIMINGS, key=lambda x: x["elapsed_ms"], reverse=True)
        if sorted_t:
            print(f"  │   Más lenta: {sorted_t[0]['endpoint']} ({sorted_t[0]['elapsed_ms']}ms)")

    print(f"  └──────────────────────────────────────")
    print(f"\n  🎮 E2E TEST COMPLETE — {len(buildings)} edificios, TH Lvl {th_final}, "
          f"{troop_total} tropas, Hero Lvl{hero.get('Level', '?')}")
    print(f"  💰 Gold safety net: {GOLD_USED}/{GOLD_SAFETY_NET} spent | "
          f"First gold at TH Lvl {GOLD_FIRST_TH_LEVEL or 'NUNCA'}")
    print(f"  📦 Items: {ITEMS_OBTAINED_COUNT} obtained, {ITEMS_USED_COUNT} used "
          f"({ITEMS_OBTAINED_COUNT - ITEMS_USED_COUNT} net)")
else:
    print(f"  ❌ No se pudo obtener estado final")

# ── Generate timing report ───────────────────────────────────────────
generate_timing_report()
